### ISSUE TITLE
XMLHttpRequest cannot load

### ISSUE THREAD

**Issue by afnizarnur** [briancavalier/slides#9]
I had some issue when opening index.html locally and it make the slide not work.

![screen shot 2017-04-02 at 9 15 18 am](https://cloud.githubusercontent.com/assets/4648648/24583922/ee820d3e-1784-11e7-85ff-a83734f148bb.png)

**Comment by briancavalier** [comment]
Hi @afnizarnur.  Chrome disallows `file` protocol urls via XHR by default.  One thing you can do is [to start Chrome with `--allow-file-access-from-files`](http://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode).

Hope that helps.

**Comment by afnizarnur** [comment]
Thanks man! @briancavalier 👍 
I try different solution to solve this problem using <a href="https://www.npmjs.com/package/http-server">http-server</a> and it's works too.

**Comment by briancavalier** [comment]
No problem, glad you found a solution. Cheers!
